---

- name: Ensure systemd reloaded
  service:
    daemon_reload: yes

- name: Ensure Gitea services stopped
  service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ gitea_services_list }}"

- name: Ensure Gitea services started
  service:
    name: "{{ item }}"
    enabled: yes
    state: "started"
  with_items: "{{ gitea_services_list }}"
