---

- name: Ensure systemd reloaded
  ansible.builtin.service:
    daemon_reload: true

- name: Ensure Gitea services stopped
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
  with_items: "{{ gitea_services_list }}"

- name: Ensure Gitea services started
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: "started"
  with_items: "{{ gitea_services_list }}"
